#!/usr/bin/env python

import os, sys, subprocess

args = sys.argv[1:]
env = dict(os.environ)
env['PYTHONPATH'] = '.:../restish:../schemaish:../formish:../formishbuilder:../validatish:../convertish:../couchdb-session:../dottedish:../jsonish:../pollen'
subprocess.call(args, env=env)

